/*
 * What API
 * This is what-api
 *
 * OpenAPI spec version: 1.2.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhatApi);
  }
}(this, function(expect, WhatApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('YtVideoItem', function() {
      beforeEach(function() {
        instance = new WhatApi.YtVideoItem();
      });

      it('should create an instance of YtVideoItem', function() {
        // TODO: update the code to test YtVideoItem
        expect(instance).to.be.a(WhatApi.YtVideoItem);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property videoId (base name: "videoId")', function() {
        // TODO: update the code to test the property videoId
        expect(instance).to.have.property('videoId');
        // expect(instance.videoId).to.be(expectedValueLiteral);
      });

      it('should have the property thumbnailUrl (base name: "thumbnailUrl")', function() {
        // TODO: update the code to test the property thumbnailUrl
        expect(instance).to.have.property('thumbnailUrl');
        // expect(instance.thumbnailUrl).to.be(expectedValueLiteral);
      });

    });
  });

}));
