/*
 * What API
 * This is what-api
 *
 * OpenAPI spec version: 1.2.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The SimpleResponse model module.
 * @module model/SimpleResponse
 * @version 1.2.1
 */
export class SimpleResponse {
  /**
   * Constructs a new <code>SimpleResponse</code>.
   * @alias module:model/SimpleResponse
   * @class
   * @param message {String} 
   */
  constructor(message) {
    this.message = message;
  }

  /**
   * Constructs a <code>SimpleResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SimpleResponse} obj Optional instance to populate.
   * @return {module:model/SimpleResponse} The populated <code>SimpleResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SimpleResponse();
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} message
 */
SimpleResponse.prototype.message = undefined;

/**
 * @member {Object} data
 */
SimpleResponse.prototype.data = undefined;


