/*
 * What API
 * This is what-api
 *
 * OpenAPI spec version: 1.2.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The TagItem model module.
 * @module model/TagItem
 * @version 1.2.1
 */
export class TagItem {
  /**
   * Constructs a new <code>TagItem</code>.
   * @alias module:model/TagItem
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>TagItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TagItem} obj Optional instance to populate.
   * @return {module:model/TagItem} The populated <code>TagItem</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TagItem();
      if (data.hasOwnProperty('_id'))
        obj.id = ApiClient.convertToType(data['_id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
TagItem.prototype.id = undefined;

/**
 * @member {String} name
 */
TagItem.prototype.name = undefined;


