/*
 * What API
 * This is what-api
 *
 * OpenAPI spec version: 1.2.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The UserPost model module.
 * @module model/UserPost
 * @version 1.2.1
 */
export class UserPost {
  /**
   * Constructs a new <code>UserPost</code>.
   * @alias module:model/UserPost
   * @class
   * @param email {String} 
   * @param password {String} 
   */
  constructor(email, password) {
    this.email = email;
    this.password = password;
  }

  /**
   * Constructs a <code>UserPost</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserPost} obj Optional instance to populate.
   * @return {module:model/UserPost} The populated <code>UserPost</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserPost();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
UserPost.prototype.email = undefined;

/**
 * @member {String} password
 */
UserPost.prototype.password = undefined;


