/*
 * What API
 * This is what-api
 *
 * OpenAPI spec version: 1.2.1
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhatApi);
  }
}(this, function(expect, WhatApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhatApi.DevelopersApi();
  });

  describe('(package)', function() {
    describe('DevelopersApi', function() {
      describe('signInUser', function() {
        it('should call signInUser successfully', function(done) {
          // TODO: uncomment, update parameter values for signInUser call and complete the assertions
          /*
          var opts = {};
          opts.userCredentials = new WhatApi.UserPost();
          opts.userCredentials.email = "mylogin@service.com";
          opts.userCredentials.password = "pa$$word";

          instance.signInUser(opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(WhatApi.SimpleResponse);
            expect(data.message).to.be.a('string');
            // expect(data.message).to.be("Request has been processed");
            expect(data.data).to.be.a(Object);
            // expect(data.data).to.be();

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('signUpUser', function() {
        it('should call signUpUser successfully', function(done) {
          // TODO: uncomment, update parameter values for signUpUser call and complete the assertions
          /*
          var opts = {};
          opts.userCredentials = new WhatApi.UserPost();
          opts.userCredentials.email = "mylogin@service.com";
          opts.userCredentials.password = "pa$$word";

          instance.signUpUser(opts).then(function(data) {
            // TODO: update response assertions
            expect(data).to.be.a(WhatApi.SimpleResponse);
            expect(data.message).to.be.a('string');
            // expect(data.message).to.be("Request has been processed");
            expect(data.data).to.be.a(Object);
            // expect(data.data).to.be();

            done();
          }, function(error) {
            done(error);
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
