/**
 * What API
 * This is what-api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd && false) {
    // AMD. Register as an anonymous module.
    // define(['ApiClient', 'model/NoteItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/NoteItem'));
  } else {
    // Browser globals (root is window)
    if (!root.WhatApi) {
      root.WhatApi = {};
    }
    root.WhatApi.DevelopersApi = factory(root.WhatApi.ApiClient, root.WhatApi.NoteItem);
  }
}(this, function(ApiClient, NoteItem) {
  'use strict';

  /**
   * Developers service.
   * @module api/DevelopersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DevelopersApi. 
   * @alias module:api/DevelopersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the searchNote operation.
     * @callback module:api/DevelopersApi~searchNoteCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/NoteItem>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * searches note
     * By passing in the appropriate options, you can search for available note in the system 
     * @param {Object} opts Optional parameters
     * @param {String} opts.id note id
     * @param {Number} opts.skip number of records to skip for pagination
     * @param {Number} opts.limit maximum number of records to return
     * @param {module:api/DevelopersApi~searchNoteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/NoteItem>}
     */
    this.searchNote = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'id': opts['id'],
        'skip': opts['skip'],
        'limit': opts['limit'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [NoteItem];

      return this.apiClient.callApi(
        '/note', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
